{
 "title": "_Backup details",
 "time": { "from": "2019-02-15T15:06:11.000Z", "to": "2019-02-15T15:22:40.000Z" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "UUID",
    "label": "UUID",
    "query": "SELECT u1 FROM backup GROUP BY u1;"
   }
  ]
 },
 "panels": [
  {
   "title": "PXB Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "rss{uuid=\"$UUID\"}",
     "legendFormat": "RSS",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timestamp) as time_sec,\n  value as value,\n  'rss' as metric\nFROM backup_rss\nWHERE $__timeFilter(timestamp) and u1='$UUID'\nORDER BY timestamp ASC\n"
    },
    {
     "expr": "vsz{uuid=\"$UUID\"}",
     "legendFormat": "VSS",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timestamp) as time_sec,\n  value as value,\n  'vsz' as metric\nFROM backup_vsz\nWHERE $__timeFilter(timestamp) and u1='$UUID'\nORDER BY timestamp ASC\n"
    }
   ]
  },
  {
   "title": "PXB Process CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu_percentage{uuid=\"$UUID\"}",
     "legendFormat": "%CPU",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timestamp) as time_sec,\n  value as value,\n  'backup_cpu_percentage' as metric\nFROM backup_cpu_percentage\nWHERE $__timeFilter(timestamp) and u1='$UUID'\nORDER BY timestamp ASC\n"
    }
   ]
  },
  {
   "title": "Threads usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Thread number" }
   ],
   "targets": [
    {
     "expr": "backup_tables{uuid=\"$UUID\"}",
     "legendFormat": "{{table}}",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timestamp) as time_sec,\n  value as value,\n  u2 as metric\nFROM backup_tables \nWHERE $__timeFilter(timestamp) and u1='$UUID'\nORDER BY timestamp ASC\n"
    }
   ]
  },
  {
   "title": "Read/Write operations (rchar/wchar)",
   "type": "graph",
   "description": "It presents the number of bytes which this task has caused to be read\n                     from storage.  This is simply the sum of bytes which this\n                     process  passed  to read and similar system calls.  It\n                     includes things such as terminal I/O and is unaffected by\n                     whether or not actual physical disk I/O was required (the\n                     read might have been satisfied from pagecache).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(rchar{uuid=\"$UUID\"}[1m])",
     "legendFormat": "Read",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timestamp) as time_sec,\n  value as value,\n  'rchar' as metric\nFROM backup_rchar\nWHERE $__timeFilter(timestamp) and u1='$UUID'\nORDER BY timestamp ASC\n"
    },
    {
     "expr": "rate(wchar{uuid=\"$UUID\"}[1m])",
     "legendFormat": "Write",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timestamp) as time_sec,\n  value as value,\n  'wchar' as metric\nFROM backup_wchar\nWHERE $__timeFilter(timestamp) and u1='$UUID'\nORDER BY timestamp ASC\n"
    }
   ]
  },
  {
   "title": "Read/Write operations (write/read_bytes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(read_bytes{uuid=\"$UUID\"}[1m])",
     "legendFormat": "Read",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timestamp) as time_sec,\n  value as value,\n  'rb' as metric\nFROM backup_read_bytes\nWHERE $__timeFilter(timestamp) and u1='$UUID'\nORDER BY timestamp ASC\n"
    },
    {
     "expr": "rate(write_bytes{uuid=\"$UUID\"}[1m])",
     "legendFormat": "Write",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timestamp) as time_sec,\n  value as value,\n  'wb' as metric\nFROM backup_write_bytes\nWHERE $__timeFilter(timestamp) and u1='$UUID'\nORDER BY timestamp ASC\n"
    }
   ]
  },
  {
   "title": "Stream backup speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "legendFormat": "Output speed",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timestamp) as time_sec,\n  value as value,\n  'backup_speed' as metric\nFROM backup_speed\nWHERE $__timeFilter(timestamp) and u1='$UUID'\nORDER BY timestamp ASC\n"
    }
   ]
  },
  {
   "title": "Processed LSN",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(backup_lsn{uuid=\"$UUID\"}[1m])",
     "legendFormat": "LSN",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timestamp) as time_sec,\n  value as value,\n  'backup_lsn' as metric\nFROM backup_lsn\nWHERE $__timeFilter(timestamp) and u1='$UUID'\nORDER BY timestamp ASC\n"
    }
   ]
  }
 ]
}